"""empty message

Revision ID: 1e8aa10f4b13
Revises: 593407ed9ede
Create Date: 2023-08-23 20:12:56.295621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e8aa10f4b13'
down_revision = '593407ed9ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('mass',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('hair_Color',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('skin_Color',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('homeworld',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('homeworld',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('skin_Color',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('hair_Color',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('mass',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###
