"""empty message

Revision ID: 593407ed9ede
Revises: 7c597ada7cb0
Create Date: 2023-08-23 20:11:34.179891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593407ed9ede'
down_revision = '7c597ada7cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('birth_year', sa.String(length=250), nullable=True),
    sa.Column('species', sa.String(length=250), nullable=True),
    sa.Column('height', sa.String(length=250), nullable=False),
    sa.Column('mass', sa.String(length=250), nullable=False),
    sa.Column('gender', sa.String(length=250), nullable=False),
    sa.Column('hair_Color', sa.String(length=250), nullable=False),
    sa.Column('skin_Color', sa.String(length=250), nullable=False),
    sa.Column('homeworld', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('characters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('birth_year', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('species', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('height', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('mass', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('hair_Color', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('skin_Color', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('homeworld', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='characters_pkey')
    )
    op.drop_table('people')
    # ### end Alembic commands ###
